// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// URLs limpias sin caracteres especiales
const SUPABASE_URL = "https://fdhanpamtgtyeaqskikh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkaGFucGFtdGd0eWVhcXNraWtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDQ0ODYsImV4cCI6MjA1OTMyMDQ4Nn0._DrZndzilD-Y7WzzzbeDZSvcpXl8os_PcWGmGgwB4ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
